### ISSUE TITLE
Using the snippets in cest file

### ISSUE THREAD

**Issue by metalmatze** [jadb/atom-codeception-snippets#1]
Hey, have you ever used those snippets in a cest file?

I need to write something like `$I->amOnPage('/');` and before every snippet there's a `$this`. Maybe `$this` could be left out, or better adding an options to choose between cest and cept files.

What do you think?

**Comment by jadb** [comment]
You got a point there and I like the idea of having an option to choose. 

I, however, am not sure of how to best implement that... I will look around but if you have any pointers let me know and if you know how to do it, go ahead ;)
